#!/usr/bin/env python3
"""
Update sample path references in Deluge XML files based on a migration map.

This script reads the migration map generated by scan-samples.py and updates
all XML files (KITS, SYNTHS, SONGS) to reflect the new sample locations.

Usage:
    # Preview changes without modifying files
    python scripts/update-refs.py --dry-run
    
    # Apply changes (creates backups by default)
    python scripts/update-refs.py
    
    # Apply changes without backups (if using version control)
    python scripts/update-refs.py --no-backup

IMPORTANT: This script MODIFIES XML files. Always use --dry-run first and
ensure you have backups (via git or --backup flag).

Known Limitations:
    - The deluge_sdk.py is a work in progress and may not handle all firmware versions
    - This script uses direct text replacement as a more robust alternative to XML parsing
    - Case sensitivity: Deluge paths are case-sensitive; this script preserves case
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from datetime import datetime
from typing import Iterator


# =============================================================================
# Configuration
# =============================================================================

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
DELUGE_DIR = PROJECT_ROOT / "DELUGE"
DOCS_DIR = PROJECT_ROOT / "docs"

# Directories containing XML files to update
XML_DIRS = [
    DELUGE_DIR / "KITS",
    DELUGE_DIR / "SYNTHS", 
    DELUGE_DIR / "SONGS",
]

MIGRATION_MAP_FILE = "sample-migration-map.json"
BACKUP_SUFFIX = ".bak"


# =============================================================================
# XML Discovery
# =============================================================================

def find_xml_files(directories: list[Path]) -> Iterator[Path]:
    """
    Find all XML files in the specified directories (recursive).
    
    Args:
        directories: List of directories to search
        
    Yields:
        Path objects for each XML file found
    """
    for directory in directories:
        if directory.exists():
            for xml_path in directory.rglob('*.XML'):
                yield xml_path
            # Also check for lowercase extension
            for xml_path in directory.rglob('*.xml'):
                yield xml_path


# =============================================================================
# Reference Detection
# =============================================================================

def find_sample_references(xml_content: str) -> list[tuple[str, int, int]]:
    """
    Find all sample path references in XML content.
    
    Handles multiple XML formats:
    - <fileName>SAMPLES/path/file.wav</fileName>
    - fileName="SAMPLES/path/file.wav"
    - filePath="SAMPLES/path/file.wav"
    
    Args:
        xml_content: Raw XML file content
        
    Returns:
        List of (path, start_pos, end_pos) tuples for each reference found
    """
    references = []
    
    # Pattern 1: <fileName>SAMPLES/...</fileName>
    # Capture the path between tags
    pattern1 = re.compile(r'<fileName>(SAMPLES/[^<]+)</fileName>', re.IGNORECASE)
    for match in pattern1.finditer(xml_content):
        path = match.group(1)
        # Get position of just the path, not the tags
        start = match.start(1)
        end = match.end(1)
        references.append((path, start, end))
    
    # Pattern 2: fileName="SAMPLES/..."
    pattern2 = re.compile(r'fileName="(SAMPLES/[^"]+)"', re.IGNORECASE)
    for match in pattern2.finditer(xml_content):
        path = match.group(1)
        start = match.start(1)
        end = match.end(1)
        references.append((path, start, end))
    
    # Pattern 3: filePath="SAMPLES/..."
    pattern3 = re.compile(r'filePath="(SAMPLES/[^"]+)"', re.IGNORECASE)
    for match in pattern3.finditer(xml_content):
        path = match.group(1)
        start = match.start(1)
        end = match.end(1)
        references.append((path, start, end))
    
    # Sort by position (important for replacement)
    references.sort(key=lambda x: x[1])
    
    return references


def normalize_path(path: str) -> str:
    """
    Normalize a sample path for comparison.
    
    - Converts backslashes to forward slashes
    - Does NOT change case (Deluge is case-sensitive)
    
    Args:
        path: Sample path from XML
        
    Returns:
        Normalized path
    """
    return path.replace('\\', '/')


# =============================================================================
# Reference Update
# =============================================================================

def update_references(xml_content: str, migration_map: dict[str, str]) -> tuple[str, list[tuple[str, str]]]:
    """
    Update sample references in XML content based on migration map.
    
    Args:
        xml_content: Raw XML file content
        migration_map: Dict mapping old_path -> new_path
        
    Returns:
        Tuple of (updated_content, list of (old_path, new_path) changes made)
    """
    references = find_sample_references(xml_content)
    changes = []
    
    if not references:
        return xml_content, changes
    
    # Build normalized lookup map
    normalized_map = {}
    for old_path, new_path in migration_map.items():
        normalized_map[normalize_path(old_path)] = new_path
    
    # Process references in reverse order to preserve positions
    result = xml_content
    for path, start, end in reversed(references):
        normalized = normalize_path(path)
        if normalized in normalized_map:
            new_path = normalized_map[normalized]
            result = result[:start] + new_path + result[end:]
            changes.append((path, new_path))
    
    # Reverse changes list to match original order
    changes.reverse()
    
    return result, changes


def process_xml_file(
    xml_path: Path,
    migration_map: dict[str, str],
    dry_run: bool = True,
    create_backup: bool = True,
) -> dict:
    """
    Process a single XML file, updating sample references.
    
    Args:
        xml_path: Path to the XML file
        migration_map: Dict mapping old_path -> new_path
        dry_run: If True, don't modify the file
        create_backup: If True, create .bak file before modifying
        
    Returns:
        Dict with processing results:
        {
            "path": str,
            "changes": [(old, new), ...],
            "error": str or None
        }
    """
    result = {
        "path": str(xml_path),
        "changes": [],
        "error": None,
    }
    
    try:
        # Read file content
        with open(xml_path, 'r', encoding='utf-8') as f:
            original_content = f.read()
    except UnicodeDecodeError:
        # Try with latin-1 as fallback
        try:
            with open(xml_path, 'r', encoding='latin-1') as f:
                original_content = f.read()
        except Exception as e:
            result["error"] = f"Could not read file: {e}"
            return result
    except Exception as e:
        result["error"] = f"Could not read file: {e}"
        return result
    
    # Find and update references
    updated_content, changes = update_references(original_content, migration_map)
    result["changes"] = changes
    
    if not changes:
        return result
    
    if dry_run:
        return result
    
    # Create backup if requested
    if create_backup:
        backup_path = xml_path.with_suffix(xml_path.suffix + BACKUP_SUFFIX)
        try:
            shutil.copy2(xml_path, backup_path)
        except Exception as e:
            result["error"] = f"Could not create backup: {e}"
            return result
    
    # Write updated content
    try:
        with open(xml_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)
    except Exception as e:
        result["error"] = f"Could not write file: {e}"
        # Try to restore from backup
        if create_backup and backup_path.exists():
            try:
                shutil.copy2(backup_path, xml_path)
            except:
                pass
        return result
    
    return result


# =============================================================================
# Reporting
# =============================================================================

def print_summary(results: list[dict], dry_run: bool) -> None:
    """Print summary of processing results."""
    files_with_changes = [r for r in results if r["changes"]]
    files_with_errors = [r for r in results if r["error"]]
    total_changes = sum(len(r["changes"]) for r in results)
    
    print(f"\n{'DRY RUN - ' if dry_run else ''}Summary:")
    print(f"  Files scanned:    {len(results)}")
    print(f"  Files with changes: {len(files_with_changes)}")
    print(f"  Total references updated: {total_changes}")
    
    if files_with_errors:
        print(f"\n  ERRORS: {len(files_with_errors)} files had errors:")
        for r in files_with_errors:
            print(f"    {r['path']}: {r['error']}")


def print_detailed_changes(results: list[dict]) -> None:
    """Print detailed list of all changes."""
    files_with_changes = [r for r in results if r["changes"]]
    
    if not files_with_changes:
        print("\nNo changes needed - all references are up to date.")
        return
    
    print("\nDetailed changes:")
    for r in files_with_changes:
        rel_path = Path(r["path"]).relative_to(PROJECT_ROOT) if PROJECT_ROOT in Path(r["path"]).parents else r["path"]
        print(f"\n  {rel_path}:")
        for old_path, new_path in r["changes"]:
            print(f"    - {old_path}")
            print(f"    + {new_path}")


# =============================================================================
# CLI
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Update sample path references in Deluge XML files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Preview what would be changed
    python scripts/update-refs.py --dry-run
    
    # Apply changes with automatic backups
    python scripts/update-refs.py
    
    # Apply changes without backups (if using git)
    python scripts/update-refs.py --no-backup
    
    # Use a custom migration map
    python scripts/update-refs.py --migration-map custom-map.json

Workflow:
    1. Run: python scripts/scan-samples.py --before
    2. Reorganize your SAMPLES folder
    3. Run: python scripts/scan-samples.py --after
    4. Run: python scripts/update-refs.py --dry-run
    5. Run: python scripts/update-refs.py
        """
    )
    
    parser.add_argument(
        '--migration-map',
        type=Path,
        default=DOCS_DIR / MIGRATION_MAP_FILE,
        help=f'Path to migration map JSON (default: docs/{MIGRATION_MAP_FILE})'
    )
    parser.add_argument(
        '--xml-dirs',
        type=Path,
        nargs='+',
        default=XML_DIRS,
        help='Directories containing XML files to update'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Preview changes without modifying any files'
    )
    parser.add_argument(
        '--no-backup',
        action='store_true',
        help='Do not create .bak files (use if you have git)'
    )
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Show detailed changes for each file'
    )
    parser.add_argument(
        '--quiet',
        action='store_true',
        help='Suppress progress output'
    )
    
    args = parser.parse_args()
    
    # Load migration map
    if not args.migration_map.exists():
        print(f"ERROR: Migration map not found: {args.migration_map}", file=sys.stderr)
        print("\nRun scan-samples.py first to generate the migration map:", file=sys.stderr)
        print("  python scripts/scan-samples.py --before", file=sys.stderr)
        print("  # Reorganize your samples", file=sys.stderr)
        print("  python scripts/scan-samples.py --after", file=sys.stderr)
        sys.exit(1)
    
    try:
        with open(args.migration_map, 'r', encoding='utf-8') as f:
            migration_data = json.load(f)
    except Exception as e:
        print(f"ERROR: Could not load migration map: {e}", file=sys.stderr)
        sys.exit(1)
    
    migration_map = migration_data.get("moves", {})
    ambiguous = migration_data.get("ambiguous", {})
    
    if not migration_map:
        print("No file moves found in migration map.")
        if ambiguous:
            print(f"\nWARNING: {len(ambiguous)} ambiguous entries (duplicate files) were skipped.")
            print("Review the 'ambiguous' section in the migration map and handle manually if needed.")
        sys.exit(0)
    
    if ambiguous:
        print(f"WARNING: {len(ambiguous)} ambiguous entries will be skipped (duplicate files).")
        print("Review the migration map and handle these manually if needed.\n")
    
    # Find all XML files
    if not args.quiet:
        print(f"Scanning for XML files in: {', '.join(str(d) for d in args.xml_dirs)}")
    
    xml_files = list(find_xml_files(args.xml_dirs))
    
    if not xml_files:
        print("No XML files found.")
        sys.exit(0)
    
    if not args.quiet:
        print(f"Found {len(xml_files)} XML files to process...")
        print(f"Migration map contains {len(migration_map)} path changes.\n")
    
    # Process each file
    results = []
    for i, xml_path in enumerate(xml_files, 1):
        if not args.quiet and i % 10 == 0:
            print(f"  Processing {i}/{len(xml_files)}...")
        
        result = process_xml_file(
            xml_path,
            migration_map,
            dry_run=args.dry_run,
            create_backup=not args.no_backup,
        )
        results.append(result)
    
    # Print results
    if args.verbose or args.dry_run:
        print_detailed_changes(results)
    
    print_summary(results, args.dry_run)
    
    if args.dry_run:
        files_with_changes = [r for r in results if r["changes"]]
        if files_with_changes:
            print(f"\nTo apply these changes, run:")
            print(f"  python scripts/update-refs.py" + (" --no-backup" if args.no_backup else ""))


if __name__ == '__main__':
    main()
